version: 2

jobs:
  # Define the checkout job
  checkout:
    docker:
      - image: node:8.6.0
    steps:
      # Using the `checkout` step, CircleCI will checkout your repository
      - checkout

      # Using the `persist_to_workspace` step, CircleCI will store your changes for the next job
      - persist_to_workspace:
          root: ~/
          paths:
            - ./*

  # Define the node job
  node:
      docker:
        - image: node:8.6.0
      steps:
        # Using the `attach_workspace` step, CircleCI will restore your changes
        - attach_workspace:
            at: ~/
        # Using the `run` step, one can execute arbitrary commands
        - run:
            name: Download Node dependencies
            working_directory: frontend/
            command: yarn install
        - run:
            name: Run Node tests
            working_directory: frontend/
            command: yarn test

  # Define the scala job
  scala:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      # Using the `attach_workspace` step, CircleCI will restore your changes
      - attach_workspace:
          at: ~/
      # Using the `run` step, one can execute arbitrary commands
      - run:
          name: Download Scala dependencies
          working_directory: backend/
          command: sbt -v update
      - run:
          name: Run Scala tests
          working_directory: backend/
          command: sbt test

  # Define the deploy job
  deploy:
    docker:
      - image: node:8.6.0
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Deploy
          command: bash .circleci/deploy.sh

workflows:
  # Use CircleCI API version 2
  version: 2

  # Define the `commit` workflow
  commit:
    jobs:
      - checkout
      - scala:
          requires:
            - checkout
      - node:
          requires:
            - checkout
      - deploy:
          requires:
            - scala
            - node
